### PR TITLE
build(mvnw): Add Maven CLI

### PR DESCRIPTION
**Pull request by iker-barriocanal**
Add the Maven CLI. This will be used by Craft to make releases.

_#skip-changelog_

### CODE REVIEW

**Comment by marandaneto** [comment]
its missing the other things like settings.xml, probably the .mvn folder too

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/tree/main/.mvn/wrapper
https://github.com/getsentry/sentry-java/blob/main/scripts/settings.xml
https://github.com/getsentry/sentry-java/blob/main/scripts/mvnw.cmd

**Comment by cortinico** [comment]
> its missing the other things like settings.xml, probably the .mvn folder too

The best approach would probably be:
```
brew install maven && mvn -N io.takari:maven:0.7.7:wrapper
```

from: https://github.com/takari/takari-maven-plugin

**Comment by marandaneto** [comment]
> > its missing the other things like settings.xml, probably the .mvn folder too
> 
> The best approach would probably be:
> 
> ```
> brew install maven && mvn -N io.takari:maven:0.7.7:wrapper
> ```
> 
> from: https://github.com/takari/takari-maven-plugin

yeah its a nice idea, Craft already depends on the mvn wrapper in the project though, we can do this as a follow-up

**Comment by iker-barriocanal** [comment]
Yep @codeniko; as @marandaneto says, Craft already depends on the `mvn` wrapper, so let's focus on that first and improve it later.

**Comment by codeniko** [comment]
Wrong Niko haha, @cortinico

**Review by cortinico — APPROVED** [review]

**Pull request merged**
