### PR TITLE
Make the ignoreXXX properties in SentryPluginExtension SetProperty

### PR DESCRIPTION
**Pull request by ansman**
## :scroll: Description
The changed properties are better suited as sets values should be unique.

This is technically a breaking change but a major release is coming up and I doubt it will cause any issues since it's mostly source compatible.

## :bulb: Motivation and Context
Set properties are more semantically correct since the properties are used to filter objects.

## :green_heart: How did you test it?
I ran the tests, no changes.

## :pencil: Checklist

- [X] I reviewed the submitted code
- [ ] I added tests to verify the changes
- [ ] I updated the docs if needed
- [ ] No breaking changes

### CODE REVIEW

**Comment by cortinico** [comment]
> This is technically a breaking change but a major release is coming up and I doubt it will cause any issues since it's mostly source compatible.

Agree. I'd leave this to @marandaneto and @romtsn as they're driving the 3.x release. Potentially this can be added as well over there. I'm unsure about the timeline

**Review by cortinico — APPROVED** [review]

**Comment by marandaneto** [comment]
the changes do make sense but since 3.0.0 already reached beta (avoiding breaking changes that are not urgent), I'd rather do it on v4

**Comment by marandaneto** [comment]
blocked till https://github.com/getsentry/sentry-android-gradle-plugin/pull/227 gets merged as well.
@ansman would you mind adding a changelog entry? we'd need to follow up with migration docs as well + updating the user-facing docs.
https://docs.sentry.io/platforms/android/proguard/#variant-filtering and https://docs.sentry.io/platforms/android/migration/

**Comment by ansman** [comment]
The docs does not need to be updated. You can still set the property with a list since it has an overload for `void set(@Nullable Iterable<? extends T> elements);`

Migration would only be needed if anyone is relying on the property returning a `List`, I can add that

**Comment by marandaneto** [comment]
sounds good, then have a look at `KtLint`, changelog entry and pull from `main`, CI should be happy after that.
thanks for doing that btw @ansman

**Review by marandaneto — APPROVED** [review]

**Pull request merged**
